### ISSUE TITLE
"Freeze panes" behavior unclear

### ISSUE THREAD

**Issue by myersjustinc** [standardnotes/secure-spreadsheets#28]
I'm attempting to create a sheet where the header row is frozen; i.e., it remains at the top of the window while the rest of the sheet's content scrolls up or down.

I am able to select "Freeze panes" and "Freeze rows" from the toolbar, but nothing appears to behave any differently. This is true regardless of whether or not I have selected the header row or dragged from any of the sheet's borders as I would in Excel or in Google Sheets.

I'm sure I'm missing something basic—how can I control what is frozen when the "Freeze *" options are selected?

**Comment by mobitar** [comment]
Since this editor is [derived](https://standardnotes.org/help/77/what-are-editors) from KendoUI, we would be users of this editor just the same. We can leave this open in case someone finds an answer, but for your best bet at an answer, I would ask the developers themselves: https://github.com/telerik/kendo-ui-core/issues

**Comment by myersjustinc** [comment]
Totally reasonable—thanks for the clarification! I'll check with the KendoUI team.

**Comment by myersjustinc** [comment]
Searched the KendoUI tickets with no luck. Tried a few more things this morning with a clear head, though, and you select the cell _below_ where you want the split to be—so to freeze the top row, you select a cell in the _second_ row and then click "Freeze rows". Not intuitive, but at least there's an answer. Going ahead and closing, but thanks again for your help!
